import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { cleanup, fireEvent, render, screen, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import App from '@/App'
import { createBrief } from '@/features/briefs/model/brief'
import { briefRepository } from '@/features/briefs/storage/brief-repository'
import { exportBriefKey } from '@/features/briefs/storage/share-key'

beforeEach(() => { localStorage.clear(); vi.restoreAllMocks(); vi.stubEnv('VITE_GOOGLE_MAPS_API_KEY', '') })
afterEach(() => { cleanup(); vi.unstubAllEnvs(); vi.restoreAllMocks() })

it('creates with multiple times, saves edits, exports, and resumes after remount', async () => {
  const user = userEvent.setup()
  const app = render(<App />)
  await user.click(screen.getByRole('button', { name: 'Create a brief' }))
  await user.type(screen.getByLabelText('Project name'), 'Riverside')
  await user.type(screen.getByLabelText('Client name'), 'Client A')
  await user.click(screen.getByRole('button', { name: 'Continue' }))
  const today = new Date()
  expect(screen.getByLabelText('Shoot date')).toHaveValue(`${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, '0')}-${String(today.getDate()).padStart(2, '0')}`)
  fireEvent.change(screen.getByLabelText('Shoot date'), { target: { value: '2026-09-11' } })
  const shootTime = screen.getByRole('slider', { name: 'Shoot time 1' })
  shootTime.focus()
  await user.keyboard('{End}')
  expect(shootTime).toHaveAttribute('aria-valuetext', '23:30')
  await user.keyboard('{Home}{ArrowRight}')
  expect(shootTime).toHaveAttribute('aria-valuetext', '00:30')
  await user.click(screen.getByRole('button', { name: 'Add time' }))
  await user.click(screen.getByRole('button', { name: 'Create brief' }))
  expect(screen.getByText('Saved on this device')).toBeInTheDocument()
  expect(briefRepository.latest()?.project.times).toEqual(['00:30', '12:00'])
  expect(briefRepository.latest()?.coordinates).toEqual({ lat: 59.9139, lng: 10.7522 })
  expect(screen.getByText('Map setup pending')).toBeInTheDocument()
  await user.click(screen.getByRole('button', { name: 'Circle rig' }))
  await user.click(screen.getByRole('button', { name: 'Add Circle Rig' }))
  const radius = screen.getByLabelText('Radius (m)')
  await user.clear(radius); await user.type(radius, '85')
  expect(briefRepository.latest()?.circleRig?.radiusMeters).toBe(85)
  expect(radius).toHaveFocus()
  fireEvent.change(radius, { target: { value: '-1' } })
  expect(briefRepository.latest()?.circleRig?.radiusMeters).toBe(85)
  await user.tab()
  expect(radius).toHaveValue(85)
  await user.click(screen.getByRole('button', { name: 'Export' }))
  expect((screen.getByLabelText('Export key') as HTMLTextAreaElement).value).toMatch(/^DB2\./)
  app.unmount()
  render(<App />)
  await user.click(screen.getByRole('button', { name: 'Resume editing' }))
  await user.click(screen.getByRole('button', { name: 'Circle rig' }))
  expect(screen.getByLabelText('Radius (m)')).toHaveValue(85)
})

it('loads a viewer and toggles layers without writing or replacing the local draft', async () => {
  const own = createBrief({ name: 'My draft', clientName: 'Owner', date: '2026-09-11', times: ['09:00'] })
  briefRepository.save(own)
  const shared = createBrief({ name: 'Shared shoot', clientName: 'Other client', date: '2026-09-12', times: ['10:00'] })
  shared.circleRig = { id: 'rig', position: shared.coordinates, arrowCount: 10, radiusMeters: 50, ovalRatio: 1, rotationDegrees: 0 }
  const writes = vi.spyOn(Storage.prototype, 'setItem')
  const user = userEvent.setup()
  render(<App />)
  await user.click(screen.getByRole('button', { name: 'Load a brief' }))
  await user.click(screen.getByLabelText('Export key'))
  await user.paste(exportBriefKey(shared))
  await user.click(screen.getByRole('button', { name: 'Open read-only brief' }))
  expect(screen.getByText('Read-only')).toBeInTheDocument()
  expect(screen.queryByRole('button', { name: 'Export' })).not.toBeInTheDocument()
  expect(screen.queryByLabelText('Latitude')).not.toBeInTheDocument()
  await user.click(screen.getByRole('button', { name: 'Project details' }))
  await user.click(screen.getByRole('button', { name: 'Camera settings' }))
  expect(screen.getByText('30, 60 m')).toBeVisible()
  await user.click(screen.getByRole('tab', { name: 'Layers' }))
  await user.click(within(screen.getByRole('region', { name: 'Brief map' })).getByRole('switch', { name: 'Circle rig' }))
  for (const toggle of screen.getAllByRole('switch', { name: 'Circle rig' })) expect(toggle).toHaveAttribute('aria-checked', 'false')
  await user.click(within(screen.getByRole('tabpanel', { name: 'Layers' })).getByRole('switch', { name: 'Circle rig' }))
  for (const toggle of screen.getAllByRole('switch', { name: 'Circle rig' })) expect(toggle).toHaveAttribute('aria-checked', 'true')
  expect(screen.queryByText(/50 m radius/)).not.toBeInTheDocument()
  expect(writes).not.toHaveBeenCalled()
  expect(briefRepository.latest()?.id).toBe(own.id)
})

it('saves live DSLR settings for existing and future points, clamps spacing, and rejects invalid input', async () => {
  const brief = createBrief({ name: 'DSLR settings', clientName: 'Test', date: '2026-09-12', times: ['12:00'] })
  brief.angles = [{ id: 'dslr', label: 'Existing DSLR', type: 'dslr', position: brief.coordinates, directionDegrees: 80 }]
  briefRepository.save(brief)
  const user = userEvent.setup()
  render(<App />)
  await user.click(screen.getByRole('button', { name: 'Resume editing' }))
  const count = screen.getByRole('spinbutton', { name: 'Number of angles' })
  const spacing = screen.getByRole('spinbutton', { name: 'Spacing (°)' })
  await user.clear(count); await user.type(count, '3')
  expect(count).toHaveFocus()
  expect(briefRepository.latest()?.typeSettings.dslr.angleCount).toBe(3)
  fireEvent.change(spacing, { target: { value: '120' } })
  fireEvent.change(count, { target: { value: '12' } })
  expect(spacing).toHaveValue(30)
  expect(spacing).toHaveAttribute('max', '30')
  fireEvent.change(spacing, { target: { value: '360' } })
  fireEvent.blur(spacing)
  expect(spacing).toHaveValue(30)
  expect(briefRepository.latest()?.typeSettings.dslr).toEqual({ heightsMeters: [1.6], angleCount: 12, spacingDegrees: 30 })
  expect(briefRepository.latest()?.angles).toEqual(brief.angles)
})

it('saves each oval radius independently and rejects values outside the oval limits', async () => {
  const brief = createBrief({ name: 'Oval', clientName: 'Test', date: '2026-09-12', times: ['12:00'] })
  brief.circleRig = { id: 'rig', position: brief.coordinates, arrowCount: 10, radiusMeters: 100, ovalRatio: 0.5, rotationDegrees: 30 }
  briefRepository.save(brief)
  const user = userEvent.setup()
  render(<App />)
  await user.click(screen.getByRole('button', { name: 'Resume editing' }))
  await user.click(screen.getByRole('button', { name: 'Circle rig' }))
  const major = screen.getByRole('spinbutton', { name: 'Biggest radius (m)' })
  const minor = screen.getByRole('spinbutton', { name: 'Smallest radius (m)' })
  fireEvent.change(major, { target: { value: '125' } })
  expect(minor).toHaveValue(50)
  expect(briefRepository.latest()?.circleRig).toEqual({ ...brief.circleRig, radiusMeters: 125, ovalRatio: 0.4 })
  fireEvent.change(minor, { target: { value: '75' } })
  expect(major).toHaveValue(125)
  expect(briefRepository.latest()?.circleRig?.ovalRatio).toBe(0.6)
  fireEvent.change(minor, { target: { value: '126' } })
  fireEvent.blur(minor)
  expect(minor).toHaveValue(75)
  fireEvent.change(major, { target: { value: '74' } })
  fireEvent.blur(major)
  expect(major).toHaveValue(125)
  expect(briefRepository.latest()?.circleRig?.rotationDegrees).toBe(30)
})

it('collapses categories without saving and only deletes a category after confirmation', async () => {
  const brief = createBrief({ name: 'Categories', clientName: 'Test', date: '2026-09-12', times: ['12:00'] })
  brief.angles = [
    { id: 'a', label: 'Drone A', type: 'drone-image', position: brief.coordinates, directionDegrees: 0 },
    { id: 'b', label: 'DSLR B', type: 'dslr', position: brief.coordinates, directionDegrees: 90 },
    { id: 'c', label: 'Drone C', type: 'drone-image', position: brief.coordinates, directionDegrees: 180 },
  ]
  briefRepository.save(brief)
  const user = userEvent.setup()
  render(<App />)
  await user.click(screen.getByRole('button', { name: 'Resume editing' }))
  const writes = vi.spyOn(Storage.prototype, 'setItem')
  await user.click(screen.getByRole('button', { name: 'Drone image points' }))
  expect(screen.queryByRole('button', { name: 'Drone image 1' })).not.toBeInTheDocument()
  expect(screen.getByRole('button', { name: 'DSLR 1' })).toBeVisible()
  await user.click(screen.getByRole('button', { name: 'Delete all Drone image points' }))
  expect(screen.getByText('Delete?')).toBeVisible()
  expect(writes).not.toHaveBeenCalled()
  await user.click(screen.getByRole('button', { name: 'Cancel deleting Drone image points' }))
  expect(briefRepository.latest()?.angles).toHaveLength(3)
  await user.click(screen.getByRole('button', { name: 'Delete all Drone image points' }))
  await user.click(screen.getByRole('button', { name: 'Confirm delete all Drone image points' }))
  expect(briefRepository.latest()?.angles.map((angle) => angle.id)).toEqual(['b'])
  expect(screen.queryByRole('button', { name: 'Drone image points' })).not.toBeInTheDocument()
  expect(screen.queryByText('Delete?')).not.toBeInTheDocument()
  await user.click(screen.getByRole('button', { name: 'Delete all DSLR points' }))
  await user.click(screen.getByRole('button', { name: 'Confirm delete all DSLR points' }))
  expect(screen.getByText('No camera points yet.')).toBeVisible()
  expect(briefRepository.latest()?.angles).toEqual([])
})

it('saves category reordering, preserves selection and resumes the new numbers', async () => {
  const brief = createBrief({ name: 'Order', clientName: 'Test', date: '2026-09-12', times: ['12:00'] })
  brief.angles = ['a', 'b', 'c'].map((id, index) => ({ id, label: 'Old name ' + id, type: 'dslr', position: { lat: 60 + index, lng: 10 }, directionDegrees: 90 }))
  briefRepository.save(brief)
  const user = userEvent.setup()
  const app = render(<App />)
  await user.click(screen.getByRole('button', { name: 'Resume editing' }))
  await user.click(screen.getByRole('button', { name: 'DSLR 3' }))
  expect(screen.queryByLabelText('Camera label')).not.toBeInTheDocument()
  const grip = screen.getByRole('button', { name: 'Reorder DSLR 3' })
  grip.focus()
  await user.keyboard('{ArrowUp}')
  expect(briefRepository.latest()?.angles.map((angle) => angle.id)).toEqual(['a', 'c', 'b'])
  expect(screen.getByRole('button', { name: 'DSLR 2' })).toHaveAttribute('aria-pressed', 'true')
  expect(screen.getByLabelText('Camera latitude')).toHaveValue(62)
  const writes = vi.spyOn(Storage.prototype, 'setItem')
  await user.click(screen.getByRole('button', { name: 'Center on DSLR 2' }))
  expect(writes).not.toHaveBeenCalled()
  app.unmount()
  render(<App />)
  await user.click(screen.getByRole('button', { name: 'Resume editing' }))
  await user.click(screen.getByRole('button', { name: 'DSLR 2' }))
  expect(screen.getByLabelText('Camera latitude')).toHaveValue(62)
})

it('shows a save failure and keeps export available', async () => {
  const own = createBrief({ name: 'My draft', clientName: 'Owner', date: '2026-09-11', times: ['09:00'] })
  briefRepository.save(own)
  vi.spyOn(Storage.prototype, 'setItem').mockImplementation(() => { throw new Error('Storage full') })
  const user = userEvent.setup()
  render(<App />)
  await user.click(screen.getByRole('button', { name: 'Resume editing' }))
  expect(screen.getByText('Not saved')).toBeInTheDocument()
  expect(screen.getByRole('alert')).toHaveTextContent('export a key')
  await user.click(screen.getByRole('button', { name: 'Export' }))
  expect((screen.getByLabelText('Export key') as HTMLTextAreaElement).value).toMatch(/^DB2\./)
})

it('removes cameras using row X and Delete while protecting text editing', async () => {
  const brief = createBrief({ name: 'Cameras', clientName: 'Client', date: '2026-09-11', times: ['09:00'] })
  brief.angles = [
    { id: 'a', label: 'Camera A', type: '360', position: brief.coordinates },
    { id: 'b', label: 'Camera B', type: 'dslr', position: brief.coordinates, directionDegrees: 90 },
  ]
  briefRepository.save(brief)
  const user = userEvent.setup()
  render(<App />)
  await user.click(screen.getByRole('button', { name: 'Resume editing' }))
  await user.click(screen.getByRole('button', { name: '360 1' }))
  await user.click(screen.getByRole('button', { name: 'Remove DSLR 1' }))
  expect(briefRepository.latest()?.angles.map((angle) => angle.id)).toEqual(['a'])
  expect(screen.queryByLabelText('Camera label')).not.toBeInTheDocument()
  fireEvent.keyDown(screen.getByLabelText('Camera latitude'), { key: 'Delete' })
  expect(briefRepository.latest()?.angles).toHaveLength(1)
  fireEvent.keyDown(window, { key: 'Delete' })
  expect(briefRepository.latest()?.angles).toEqual([])
  expect(screen.queryByLabelText('Camera label')).not.toBeInTheDocument()
})


it.each(['X', 'Delete'])('removes modifier-selected cameras with %s and preserves unselected cameras', async (method) => {
  const brief = createBrief({ name: 'Group', clientName: 'Client', date: '2026-09-11', times: ['09:00'] })
  brief.angles = ['A', 'B', 'C'].map((id) => ({ id, label: 'Camera ' + id, type: '360' as const, position: brief.coordinates }))
  briefRepository.save(brief)
  const user = userEvent.setup()
  render(<App />)
  await user.click(screen.getByRole('button', { name: 'Resume editing' }))
  await user.click(screen.getByRole('button', { name: '360 1' }))
  await user.keyboard(method === 'X' ? '{Shift>}' : '{Control>}')
  await user.click(screen.getByRole('button', { name: '360 3' }))
  await user.keyboard(method === 'X' ? '{/Shift}' : '{/Control}')
  expect(briefRepository.latest()?.angles).toHaveLength(3)
  if (method === 'X') await user.click(screen.getByRole('button', { name: 'Remove 360 1' }))
  else await user.keyboard('{Delete}')
  expect(briefRepository.latest()?.angles.map((angle) => angle.id)).toEqual(['B'])
  expect(screen.getByRole('button', { name: '360 1' })).toHaveAttribute('aria-pressed', 'false')
  expect(screen.queryByRole('checkbox')).not.toBeInTheDocument()
})

it('saves valid rig arrow counts live and restores invalid or empty input on blur', async () => {
  const brief = createBrief({ name: 'Arrows', clientName: 'Test', date: '2026-09-12', times: ['12:00'] })
  brief.circleRig = { id: 'rig', position: brief.coordinates, arrowCount: 10, radiusMeters: 50, ovalRatio: 1, rotationDegrees: 0 }
  briefRepository.save(brief)
  const user = userEvent.setup()
  render(<App />)
  await user.click(screen.getByRole('button', { name: 'Resume editing' }))
  await user.click(screen.getByRole('button', { name: 'Circle rig' }))
  const count = screen.getByRole('spinbutton', { name: 'Number of arrows' })
  expect(count).toHaveValue(10)
  fireEvent.change(count, { target: { value: '16' } })
  expect(briefRepository.latest()?.circleRig?.arrowCount).toBe(16)
  for (const value of ['', '0', '51', '2.5']) {
    fireEvent.change(count, { target: { value } })
    expect(briefRepository.latest()?.circleRig?.arrowCount).toBe(16)
    fireEvent.blur(count)
    expect(count).toHaveValue(16)
  }
})
