import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { cleanup, fireEvent, render, screen, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import App from '@/App'
import { createBrief } from '@/features/briefs/model/brief'
import { briefRepository } from '@/features/briefs/storage/brief-repository'
import { exportBriefKey } from '@/features/briefs/storage/share-key'

// Exercise local drafts even when the developer has configured a live Firebase project.
vi.mock('@/features/cloud/auth/config', () => ({ cloudConfigured: false }))

beforeEach(() => { localStorage.clear(); vi.restoreAllMocks(); vi.stubEnv('VITE_GOOGLE_MAPS_API_KEY', '') })
afterEach(() => { cleanup(); vi.unstubAllEnvs(); vi.restoreAllMocks() })

it('creates without a schedule step, saves stacked shadow times, exports, and resumes after remount', async () => {
  const user = userEvent.setup()
  const app = render(<App />)
  await user.click(screen.getByRole('button', { name: 'Create a brief' }))
  await user.type(screen.getByLabelText('Project name'), 'Riverside')
  await user.type(screen.getByLabelText('Client name'), 'Client A')
  expect(screen.queryByLabelText('Shoot date')).not.toBeInTheDocument()
  await user.click(screen.getByRole('button', { name: 'Create brief' }))
  expect(screen.getByText('Saved on this device')).toBeInTheDocument()
  const today = `${new Date().getFullYear()}-${String(new Date().getMonth() + 1).padStart(2, '0')}-${String(new Date().getDate()).padStart(2, '0')}`
  expect(briefRepository.latest()?.project.times).toEqual(['09:00'])
  expect(briefRepository.latest()?.project.date).toBe(today)
  expect(screen.getByRole('slider', { name: 'Shadow time' })).toBeInTheDocument()
  fireEvent.change(screen.getByLabelText('Shadow date'), { target: { value: '2026-09-11' } })
  await user.click(screen.getByRole('button', { name: 'Add time' }))
  expect(briefRepository.latest()?.project.times).toEqual(['09:00', '09:15'])
  expect(briefRepository.latest()?.project.shoots).toEqual([
    { date: '2026-09-11', time: '09:00' }, { date: '2026-09-11', time: '09:15' },
  ])
  expect(briefRepository.latest()?.coordinates).toEqual({ lat: 59.9139, lng: 10.7522 })
  expect(screen.getByText('Map setup pending')).toBeInTheDocument()
  expect(screen.getByRole('heading', { name: 'Riverside' })).toBeVisible()
  expect(screen.getByText('Client A')).toBeVisible()
  expect(screen.queryByText('Project name')).not.toBeInTheDocument()
  expect(screen.queryByLabelText('Project name')).not.toBeInTheDocument()
  await user.click(screen.getByRole('button', { name: 'Edit title' }))
  expect(screen.getByLabelText('Project name')).toHaveValue('Riverside')
  await user.clear(screen.getByLabelText('Client name'))
  await user.type(screen.getByLabelText('Client name'), 'Client B')
  await user.tab()
  expect(briefRepository.latest()?.project.clientName).toBe('Client B')
  expect(screen.getByRole('heading', { name: 'Riverside' })).toBeVisible()
  expect(screen.getByText('Client B')).toBeVisible()
  await user.click(screen.getByRole('tab', { name: 'Contents' }))
  await user.type(screen.getByLabelText('Property information'), 'South facade')
  fireEvent.blur(screen.getByLabelText('Property information'))
  await user.type(screen.getByLabelText('Instructions'), 'Use the rear gate')
  fireEvent.blur(screen.getByLabelText('Instructions'))
  expect(briefRepository.latest()?.project.description).toBe('South facade')
  expect(briefRepository.latest()?.project.instructions).toBe('Use the rear gate')
  await user.click(screen.getByRole('tab', { name: 'Project' }))
  await user.click(screen.getByRole('button', { name: 'Add Circle Rig' }))
  const radius = screen.getByLabelText('Radius (m)')
  await user.clear(radius); await user.type(radius, '85')
  expect(briefRepository.latest()?.circleRig?.radiusMeters).toBe(85)
  expect(radius).toHaveFocus()
  fireEvent.change(radius, { target: { value: '-1' } })
  expect(briefRepository.latest()?.circleRig?.radiusMeters).toBe(85)
  await user.tab()
  expect(radius).toHaveValue(85)
  await user.click(screen.getByRole('button', { name: 'Export key' }))
  expect((screen.getByLabelText('Export key') as HTMLTextAreaElement).value).toMatch(/^DB2\./)
  app.unmount()
  render(<App />)
  await user.click(screen.getByRole('button', { name: 'Resume editing' }))
  expect(screen.getByLabelText('Radius (m)')).toHaveValue(85)
}, 15000)

it('loads a viewer and toggles layers without writing or replacing the local draft', async () => {
  const own = createBrief({ name: 'My draft', clientName: 'Owner', date: '2026-09-11', times: ['09:00'] })
  briefRepository.save(own)
  const shared = createBrief({ name: 'Shared shoot', clientName: 'Other client', date: '2026-09-12', times: ['10:00'] })
  shared.circleRig = { id: 'rig', position: shared.coordinates, arrowCount: 10, radiusMeters: 50, ovalRatio: 1, rotationDegrees: 0 }
  const writes = vi.spyOn(Storage.prototype, 'setItem')
  const user = userEvent.setup()
  render(<App />)
  await user.click(screen.getByRole('button', { name: 'Load a brief' }))
  await user.click(screen.getByLabelText('Export key'))
  await user.paste(exportBriefKey(shared))
  await user.click(screen.getByRole('button', { name: 'Open read-only brief' }))
  expect(screen.getByText('Read-only')).toBeInTheDocument()
  expect(screen.getByRole('heading', { name: 'Shared shoot' })).toBeVisible()
  expect(screen.getByText('Other client')).toBeVisible()
  expect(screen.queryByRole('button', { name: 'Edit title' })).not.toBeInTheDocument()
  expect(screen.queryByRole('button', { name: 'Export key' })).not.toBeInTheDocument()
  expect(screen.queryByLabelText('Latitude')).not.toBeInTheDocument()
  expect(screen.getByText('40, 60 m')).toBeVisible()
  expect(screen.getByText('2, 5, 8 m')).toBeVisible()
  expect(screen.queryByRole('button', { name: 'Add floor (3m)' })).not.toBeInTheDocument()
  await user.click(screen.getByRole('tab', { name: 'Contents' }))
  const mapLayers = within(screen.getByRole('region', { name: 'Brief map' }))
  await user.click(mapLayers.getByRole('switch', { name: 'Circle rig' }))
  expect(mapLayers.getByRole('switch', { name: 'Circle rig' })).toHaveAttribute('aria-checked', 'false')
  await user.click(mapLayers.getByRole('switch', { name: 'Circle rig' }))
  expect(mapLayers.getByRole('switch', { name: 'Circle rig' })).toHaveAttribute('aria-checked', 'true')
  expect(screen.getByText('No property information.')).toBeVisible()
  expect(screen.getByText('No instructions.')).toBeVisible()
  expect(screen.getByRole('button', { name: 'Floor plan' })).toBeVisible()
  expect(screen.getByRole('button', { name: 'Calculate images' })).toBeVisible()
  expect(screen.queryByText(/50 m radius/)).not.toBeInTheDocument()
  const overlaySize = screen.getByRole('slider', { name: 'Overlay size' })
  overlaySize.focus()
  await user.keyboard('{End}')
  expect(overlaySize).toHaveAttribute('aria-valuenow', '300')
  await user.keyboard('{Home}{ArrowRight}')
  expect(overlaySize).toHaveAttribute('aria-valuenow', '30')
  expect(screen.getByRole('slider', { name: 'Shadow time' })).toBeInTheDocument()
  await user.click(screen.getByRole('button', { name: 'Add time' }))
  expect(screen.getByRole('slider', { name: 'Shadow time 2' })).toBeInTheDocument()
  expect(writes).not.toHaveBeenCalled()
  expect(briefRepository.latest()?.id).toBe(own.id)
})

it('defaults camera heights and appends 360 floors in 3 m steps', async () => {
  const brief = createBrief({ name: 'Floors', clientName: 'Test', date: '2026-09-12', times: ['12:00'] })
  briefRepository.save(brief)
  const user = userEvent.setup()
  render(<App />)
  await user.click(screen.getByRole('button', { name: 'Resume editing' }))
  expect(screen.getByLabelText('Drone image heights (m)')).toHaveValue('40, 60')
  const heights = screen.getByLabelText('360 heights (m)')
  expect(heights).toHaveValue('2, 5, 8')
  await user.click(heights)
  await user.keyboard('{End}{Backspace}')
  expect(briefRepository.latest()?.typeSettings['360'].heightsMeters).toEqual([2, 5])
  await user.click(screen.getByRole('button', { name: 'Add floor (3m)' }))
  expect(screen.getByLabelText('360 heights (m)')).toHaveValue('2, 5, 8')
  expect(briefRepository.latest()?.typeSettings['360'].heightsMeters).toEqual([2, 5, 8])
  await user.click(screen.getByRole('button', { name: 'Add floor (3m)' }))
  expect(screen.getByLabelText('360 heights (m)')).toHaveValue('2, 5, 8, 11')
  expect(briefRepository.latest()?.typeSettings['360'].heightsMeters).toEqual([2, 5, 8, 11])
})

it('saves live DSLR settings for existing and future points, clamps spacing, and rejects invalid input', async () => {
  const brief = createBrief({ name: 'DSLR settings', clientName: 'Test', date: '2026-09-12', times: ['12:00'] })
  brief.angles = [{ id: 'dslr', label: 'Existing DSLR', type: 'dslr', position: brief.coordinates, directionDegrees: 80 }]
  briefRepository.save(brief)
  const user = userEvent.setup()
  render(<App />)
  await user.click(screen.getByRole('button', { name: 'Resume editing' }))
  const count = screen.getByRole('spinbutton', { name: 'Number of angles' })
  const spacing = screen.getByRole('spinbutton', { name: 'Spacing (°)' })
  await user.clear(count); await user.type(count, '3')
  expect(count).toHaveFocus()
  expect(briefRepository.latest()?.typeSettings.dslr.angleCount).toBe(3)
  fireEvent.change(spacing, { target: { value: '120' } })
  fireEvent.change(count, { target: { value: '12' } })
  expect(spacing).toHaveValue(30)
  expect(spacing).toHaveAttribute('max', '30')
  fireEvent.change(spacing, { target: { value: '360' } })
  fireEvent.blur(spacing)
  expect(spacing).toHaveValue(30)
  expect(briefRepository.latest()?.typeSettings.dslr).toEqual({ heightsMeters: [1.6], angleCount: 12, spacingDegrees: 30 })
  expect(briefRepository.latest()?.angles).toEqual(brief.angles)
})

it('saves each oval radius independently and rejects values outside the oval limits', async () => {
  const brief = createBrief({ name: 'Oval', clientName: 'Test', date: '2026-09-12', times: ['12:00'] })
  brief.circleRig = { id: 'rig', position: brief.coordinates, arrowCount: 10, radiusMeters: 100, ovalRatio: 0.5, rotationDegrees: 30 }
  briefRepository.save(brief)
  const user = userEvent.setup()
  render(<App />)
  await user.click(screen.getByRole('button', { name: 'Resume editing' }))
  const major = screen.getByRole('spinbutton', { name: 'Biggest radius (m)' })
  const minor = screen.getByRole('spinbutton', { name: 'Smallest radius (m)' })
  fireEvent.change(major, { target: { value: '125' } })
  expect(minor).toHaveValue(50)
  expect(briefRepository.latest()?.circleRig).toEqual({ ...brief.circleRig, radiusMeters: 125, ovalRatio: 0.4 })
  fireEvent.change(minor, { target: { value: '75' } })
  expect(major).toHaveValue(125)
  expect(briefRepository.latest()?.circleRig?.ovalRatio).toBe(0.6)
  fireEvent.change(minor, { target: { value: '126' } })
  fireEvent.blur(minor)
  expect(minor).toHaveValue(75)
  fireEvent.change(major, { target: { value: '74' } })
  fireEvent.blur(major)
  expect(major).toHaveValue(125)
  expect(briefRepository.latest()?.circleRig?.rotationDegrees).toBe(30)
})

it('collapses categories without saving and only deletes a category after confirmation', async () => {
  const brief = createBrief({ name: 'Categories', clientName: 'Test', date: '2026-09-12', times: ['12:00'] })
  brief.angles = [
    { id: 'a', label: 'Drone A', type: 'drone-image', position: brief.coordinates, directionDegrees: 0 },
    { id: 'b', label: 'DSLR B', type: 'dslr', position: brief.coordinates, directionDegrees: 90 },
    { id: 'c', label: 'Drone C', type: 'drone-image', position: brief.coordinates, directionDegrees: 180 },
  ]
  briefRepository.save(brief)
  const user = userEvent.setup()
  render(<App />)
  await user.click(screen.getByRole('button', { name: 'Resume editing' }))
  const writes = vi.spyOn(Storage.prototype, 'setItem')
  await user.click(screen.getByRole('button', { name: 'Drone image points' }))
  expect(screen.queryByRole('button', { name: 'Drone image 1' })).not.toBeInTheDocument()
  expect(screen.getByRole('button', { name: 'DSLR 1' })).toBeVisible()
  await user.click(screen.getByRole('button', { name: 'Delete all Drone image points' }))
  expect(screen.getByText('Delete?')).toBeVisible()
  expect(writes).not.toHaveBeenCalled()
  await user.click(screen.getByRole('button', { name: 'Cancel deleting Drone image points' }))
  expect(briefRepository.latest()?.angles).toHaveLength(3)
  await user.click(screen.getByRole('button', { name: 'Delete all Drone image points' }))
  await user.click(screen.getByRole('button', { name: 'Confirm delete all Drone image points' }))
  expect(briefRepository.latest()?.angles.map((angle) => angle.id)).toEqual(['b'])
  expect(screen.queryByRole('button', { name: 'Drone image points' })).not.toBeInTheDocument()
  expect(screen.queryByText('Delete?')).not.toBeInTheDocument()
  await user.click(screen.getByRole('button', { name: 'Delete all DSLR points' }))
  await user.click(screen.getByRole('button', { name: 'Confirm delete all DSLR points' }))
  expect(screen.getByText('No camera points yet.')).toBeVisible()
  expect(briefRepository.latest()?.angles).toEqual([])
})

it('saves category reordering, preserves selection and resumes the new numbers', async () => {
  const brief = createBrief({ name: 'Order', clientName: 'Test', date: '2026-09-12', times: ['12:00'] })
  brief.angles = ['a', 'b', 'c'].map((id, index) => ({ id, label: 'Old name ' + id, type: 'dslr', position: { lat: 60 + index, lng: 10 }, directionDegrees: 90 }))
  briefRepository.save(brief)
  const user = userEvent.setup()
  const app = render(<App />)
  await user.click(screen.getByRole('button', { name: 'Resume editing' }))
  await user.click(screen.getByRole('button', { name: 'DSLR 3' }))
  expect(screen.queryByLabelText('Camera label')).not.toBeInTheDocument()
  const grip = screen.getByRole('button', { name: 'Reorder DSLR 3' })
  grip.focus()
  await user.keyboard('{ArrowUp}')
  expect(briefRepository.latest()?.angles.map((angle) => angle.id)).toEqual(['a', 'c', 'b'])
  expect(screen.getByRole('button', { name: 'DSLR 2' })).toHaveAttribute('aria-pressed', 'true')
  expect(screen.getByLabelText('Camera latitude')).toHaveValue(62)
  const writes = vi.spyOn(Storage.prototype, 'setItem')
  await user.click(screen.getByRole('button', { name: 'Center on DSLR 2' }))
  expect(writes).not.toHaveBeenCalled()
  app.unmount()
  render(<App />)
  await user.click(screen.getByRole('button', { name: 'Resume editing' }))
  await user.click(screen.getByRole('button', { name: 'DSLR 2' }))
  expect(screen.getByLabelText('Camera latitude')).toHaveValue(62)
})

it('shows a save failure and keeps export available', async () => {
  const own = createBrief({ name: 'My draft', clientName: 'Owner', date: '2026-09-11', times: ['09:00'] })
  briefRepository.save(own)
  vi.spyOn(Storage.prototype, 'setItem').mockImplementation(() => { throw new Error('Storage full') })
  const user = userEvent.setup()
  render(<App />)
  await user.click(screen.getByRole('button', { name: 'Resume editing' }))
  expect(screen.getByText('Not saved')).toBeInTheDocument()
  expect(screen.getByRole('alert')).toHaveTextContent('export a key')
  await user.click(screen.getByRole('button', { name: 'Export key' }))
  expect((screen.getByLabelText('Export key') as HTMLTextAreaElement).value).toMatch(/^DB2\./)
})

it('removes cameras using row X and Delete while protecting text editing', async () => {
  const brief = createBrief({ name: 'Cameras', clientName: 'Client', date: '2026-09-11', times: ['09:00'] })
  brief.angles = [
    { id: 'a', label: 'Camera A', type: '360', position: brief.coordinates },
    { id: 'b', label: 'Camera B', type: 'dslr', position: brief.coordinates, directionDegrees: 90 },
  ]
  briefRepository.save(brief)
  const user = userEvent.setup()
  render(<App />)
  await user.click(screen.getByRole('button', { name: 'Resume editing' }))
  await user.click(screen.getByRole('button', { name: '360 1' }))
  await user.click(screen.getByRole('button', { name: 'Remove DSLR 1' }))
  expect(briefRepository.latest()?.angles.map((angle) => angle.id)).toEqual(['a'])
  expect(screen.queryByLabelText('Camera label')).not.toBeInTheDocument()
  fireEvent.keyDown(screen.getByLabelText('Camera latitude'), { key: 'Delete' })
  expect(briefRepository.latest()?.angles).toHaveLength(1)
  fireEvent.keyDown(window, { key: 'Delete' })
  expect(briefRepository.latest()?.angles).toEqual([])
  expect(screen.queryByLabelText('Camera label')).not.toBeInTheDocument()
})


it.each(['X', 'Delete'])('removes modifier-selected cameras with %s and preserves unselected cameras', async (method) => {
  const brief = createBrief({ name: 'Group', clientName: 'Client', date: '2026-09-11', times: ['09:00'] })
  brief.angles = ['A', 'B', 'C'].map((id) => ({ id, label: 'Camera ' + id, type: '360' as const, position: brief.coordinates }))
  briefRepository.save(brief)
  const user = userEvent.setup()
  render(<App />)
  await user.click(screen.getByRole('button', { name: 'Resume editing' }))
  await user.click(screen.getByRole('button', { name: '360 1' }))
  await user.keyboard(method === 'X' ? '{Shift>}' : '{Control>}')
  await user.click(screen.getByRole('button', { name: '360 3' }))
  await user.keyboard(method === 'X' ? '{/Shift}' : '{/Control}')
  expect(briefRepository.latest()?.angles).toHaveLength(3)
  if (method === 'X') await user.click(screen.getByRole('button', { name: 'Remove 360 1' }))
  else await user.keyboard('{Delete}')
  expect(briefRepository.latest()?.angles.map((angle) => angle.id)).toEqual(['B'])
  expect(screen.getByRole('button', { name: '360 1' })).toHaveAttribute('aria-pressed', 'false')
  expect(screen.queryByRole('checkbox')).not.toBeInTheDocument()
})

it('saves valid rig arrow counts live and restores invalid or empty input on blur', async () => {
  const brief = createBrief({ name: 'Arrows', clientName: 'Test', date: '2026-09-12', times: ['12:00'] })
  brief.circleRig = { id: 'rig', position: brief.coordinates, arrowCount: 10, radiusMeters: 50, ovalRatio: 1, rotationDegrees: 0 }
  briefRepository.save(brief)
  const user = userEvent.setup()
  render(<App />)
  await user.click(screen.getByRole('button', { name: 'Resume editing' }))
  const count = screen.getByRole('spinbutton', { name: 'Number of arrows' })
  expect(count).toHaveValue(10)
  fireEvent.change(count, { target: { value: '16' } })
  expect(briefRepository.latest()?.circleRig?.arrowCount).toBe(16)
  for (const value of ['', '0', '51', '2.5']) {
    fireEvent.change(count, { target: { value } })
    expect(briefRepository.latest()?.circleRig?.arrowCount).toBe(16)
    fireEvent.blur(count)
    expect(count).toHaveValue(16)
  }
})

it('counts planned images from the locked capture rules and places the shoot date beside the times title', async () => {
  const brief = createBrief({ name: 'Images', clientName: 'Client', date: '2026-09-12', times: ['12:00'] })
  brief.circleRig = { id: 'rig', position: brief.coordinates, arrowCount: 10, radiusMeters: 50, ovalRatio: 1, rotationDegrees: 0 }
  brief.angles = [
    { id: 'd1', label: 'D1', type: 'drone-image', position: brief.coordinates, directionDegrees: 0 },
    { id: 'd2', label: 'D2', type: 'drone-image', position: brief.coordinates, directionDegrees: 90 },
    { id: 'p1', label: 'P1', type: '360', position: brief.coordinates },
    { id: 's1', label: 'S1', type: 'dslr', position: brief.coordinates, directionDegrees: 45 },
    { id: 's2', label: 'S2', type: 'dslr', position: brief.coordinates, directionDegrees: 180 },
  ]
  brief.typeSettings = { ...brief.typeSettings, dslr: { ...brief.typeSettings.dslr, angleCount: 3 } }
  briefRepository.save(brief)
  const user = userEvent.setup()
  render(<App />)
  await user.click(screen.getByRole('button', { name: 'Resume editing' }))
  expect(screen.queryByText(/2026-09-12 ·/)).not.toBeInTheDocument()
  expect(screen.getByText('Shoot times').parentElement).toHaveTextContent('2026-09-12')
  expect(screen.getByText('Shoot times').parentElement).toHaveTextContent('12:00')
  expect(screen.getByLabelText('Total images')).toHaveTextContent('60')
  expect(screen.queryByRole('button', { name: 'Project details' })).not.toBeInTheDocument()
  await user.click(screen.getByRole('tab', { name: 'Contents' }))
  const count = within(screen.getByRole('region', { name: 'Image count' }))
  expect(screen.getByRole('button', { name: 'Calculate images' })).toBeVisible()
  expect(count.getByText('1 per arrow, height, and time')).toBeVisible()
  expect(count.getByText('1 per point, height, and time')).toBeVisible()
  expect(count.getByText('10 per point, height, and time')).toBeVisible()
  expect(count.getByText('1 per arrow and time')).toBeVisible()
  expect(count.getByLabelText('Circle rig count')).toHaveTextContent('20')
  expect(count.getByLabelText('Drone image count')).toHaveTextContent('4')
  expect(count.getByLabelText('360 count')).toHaveTextContent('30')
  expect(count.getByLabelText('DSLR count')).toHaveTextContent('6')
  expect(count.getByLabelText('Image count total')).toHaveTextContent('60')
  expect(screen.queryByRole('button', { name: /Show only / })).not.toBeInTheDocument()
})
