import type { PdfLanguage } from '../export/pdf-copy'

export type BriefingCopy = (typeof briefingCopy)[PdfLanguage]

export const briefingCopy = {
  en: {
    shootTimes: 'Shoot times',
    totalImages: 'Total images',
    projectSizes: { mini: 'Mini project', small: 'Small project', medium: 'Medium project', large: 'Large project' },
    projectSizeNote: "Automatically matched to the template's point counts and height levels. Rig arrows count as aerial positions.",
    property: 'Property information',
    instructions: 'Instructions',
    emptyProperty: 'No property information.',
    emptyInstructions: 'No instructions.',
    references: 'Reference images',
    info: 'Project information',
    closeInfo: 'Close project information',
    addressNotSet: 'Address not specified',
    drone: 'Aerial photo',
    droneRule: 'Maximum height of 120m',
    panorama: '360°',
    panoramaRule: 'Not stitched panorama, individual photos',
    dslr: 'DSLR',
    dslrRule: (span: number, count: number) => `${span}°, minimum ${count} photo${count === 1 ? '' : 's'} per point`,
    ground: 'Ground-level',
    point: 'Point',
    rig: 'Circle rig',
    rigRule: '1 photo per arrow and height',
    arrows: 'Arrows',
  },
  nb: {
    shootTimes: 'Fototidspunkt',
    totalImages: 'Antall foto',
    projectSizes: { mini: 'Miniprosjekt', small: 'Lite prosjekt', medium: 'Mellomstort prosjekt', large: 'Stort prosjekt' },
    projectSizeNote: 'Automatisk tilpasset malens punktantall og høydenivåer. Rigg-piler telles som luftposisjoner.',
    property: 'Eiendom / tomt',
    instructions: 'Instruksjoner',
    emptyProperty: 'Ingen eiendomsinformasjon.',
    emptyInstructions: 'Ingen instruksjoner.',
    references: 'Referansebilder',
    info: 'Prosjektinformasjon',
    closeInfo: 'Lukk prosjektinformasjon',
    addressNotSet: 'Adresse ikke angitt',
    drone: 'Oversiktsfoto',
    droneRule: 'Maksimumshøyde 120m',
    panorama: '360°',
    panoramaRule: 'Ikke sammensatt panorama, individuelle bilder',
    dslr: 'DSLR',
    dslrRule: (span: number, count: number) => `${span}°, minst ${count} foto per punkt`,
    ground: 'Bakkenivå',
    point: 'Punkt',
    rig: 'Sirkelrigg',
    rigRule: '1 foto per pil og høyde',
    arrows: 'Piler',
  },
} as const
