import { afterEach, expect, it, vi } from 'vitest'
import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { PdfExportDialog } from './pdf-export-dialog'
import { createBrief } from '../model/brief'
import type { PdfExportInput } from '../export/pdf-types'
const mocks = vi.hoisted(() => ({ create: vi.fn(async (_input: PdfExportInput) => new Uint8Array([1])), download: vi.fn(), assets: vi.fn(async () => ({})) }))
vi.mock('../export/create-brief-pdf', () => ({ createBriefPdf: mocks.create }))
vi.mock('../export/pdf-browser', () => ({ loadPdfAssets: mocks.assets, downloadPdf: mocks.download, pdfReference: vi.fn() }))
vi.mock('@/features/map/pdf-address', () => ({ lookupPdfAddress: vi.fn(async () => 'Karl Johans gate: Oslo') }))
afterEach(() => { cleanup(); vi.clearAllMocks() })
function setup(editable = true) {
  const brief = createBrief({ name: 'Export test', clientName: 'Client', date: '2026-09-19', times: ['12:00'] })
  const capture = vi.fn(async () => [{ kind: 'map' as const, dataUrl: 'data:image/png;base64,test' }])
  const save = vi.fn(), close = vi.fn()
  render(<PdfExportDialog brief={brief} editable={editable} captureRef={{ current: capture }} onSaveNotes={save} onClose={close} />)
  return { save, close, capture, user: userEvent.setup() }
}
it('asks for missing information and only saves it after successful export', async () => {
  const { user, save } = setup()
  await user.click(screen.getByRole('button', { name: 'Norsk bokmål' }))
  await user.click(screen.getByRole('button', { name: 'Continue' }))
  expect(screen.getByText(/Some information is empty/)).toBeVisible()
  fireEvent.change(screen.getByLabelText('Property information (optional)'), { target: { value: 'Sjøtomt' } })
  await user.click(screen.getByRole('button', { name: 'Continue' }))
  expect(save).not.toHaveBeenCalled()
  await user.click(screen.getByRole('button', { name: 'Download PDF' }))
  await waitFor(() => expect(mocks.download).toHaveBeenCalled())
  expect(save).toHaveBeenCalledExactlyOnceWith({ description: 'Sjøtomt', instructions: '' })
  expect(mocks.create.mock.calls[0]?.[0]).toMatchObject({ language: 'nb', notes: { description: 'Sjøtomt', instructions: '' } })
  expect(mocks.create.mock.calls[0]?.[0].coverAddress).toBe('Karl Johans gate: Oslo')
})
it('allows empty notes and a diagram, and never mutates a read-only brief', async () => {
  const { user, save, capture } = setup(false)
  await user.click(screen.getByRole('button', { name: 'Continue' }))
  expect(screen.queryByRole('switch')).not.toBeInTheDocument()
  await user.click(screen.getByRole('button', { name: 'Continue' }))
  await user.click(screen.getByRole('button', { name: 'Point diagram' }))
  await user.click(screen.getByRole('button', { name: 'Download PDF' }))
  await waitFor(() => expect(mocks.download).toHaveBeenCalled())
  expect(capture).not.toHaveBeenCalled(); expect(save).not.toHaveBeenCalled()
})
it('keeps notes unsaved after a map failure, and permits retry with a diagram', async () => {
  const { user, save, capture } = setup()
  capture.mockRejectedValueOnce(new Error('Reconnect the floor plan.'))
  await user.click(screen.getByRole('button', { name: 'Continue' }))
  fireEvent.change(screen.getByLabelText('Instructions (optional)'), { target: { value: 'East gate' } })
  await user.click(screen.getByRole('button', { name: 'Continue' }))
  await user.click(screen.getByRole('button', { name: 'Download PDF' }))
  expect(await screen.findByRole('alert')).toHaveTextContent('Reconnect the floor plan.')
  expect(save).not.toHaveBeenCalled(); expect(mocks.download).not.toHaveBeenCalled()
  await user.click(screen.getByRole('button', { name: 'Point diagram' }))
  await user.click(screen.getByRole('button', { name: 'Download PDF' }))
  await waitFor(() => expect(mocks.download).toHaveBeenCalled())
})
it('does not save edits when the wizard is closed', async () => {
  const { user, save, close } = setup()
  await user.click(screen.getByRole('button', { name: 'Continue' }))
  fireEvent.change(screen.getByLabelText('Instructions (optional)'), { target: { value: 'Discarded' } })
  await user.click(screen.getByRole('button', { name: 'Close' }))
  expect(close).toHaveBeenCalled(); expect(save).not.toHaveBeenCalled(); expect(mocks.download).not.toHaveBeenCalled()
})
it('exports an editable custom address and previews the calculated sun times', async () => {
  const { user } = setup()
  await waitFor(() => expect(screen.getByLabelText('Street address: Area')).toHaveValue('Karl Johans gate: Oslo'))
  fireEvent.change(screen.getByLabelText('Street address: Area'), { target: { value: 'Custom street: Custom area' } })
  await user.click(screen.getByRole('button', { name: 'Continue' }))
  await user.click(screen.getByRole('button', { name: 'Continue' }))
  expect(within(screen.getByLabelText('Calculated sun times')).getByText('Daytime', { exact: true })).toBeVisible()
  expect(within(screen.getByLabelText('Calculated sun times')).queryByText('Sunrise', { exact: true })).not.toBeInTheDocument()
  expect(screen.getByLabelText('Calculated sun times')).toHaveTextContent('Europe/Oslo')
  await user.click(screen.getByRole('button', { name: 'Point diagram' }))
  await user.click(screen.getByRole('button', { name: 'Download PDF' }))
  await waitFor(() => expect(mocks.download).toHaveBeenCalled())
  expect(mocks.create.mock.calls[0]?.[0].coverAddress).toBe('Custom street: Custom area')
})
it('can omit either or both names from the cover without modifying project details', async () => {
  const { user, save } = setup()
  const preview = screen.getByLabelText('Cover preview')
  expect(preview).toHaveTextContent('Export test')
  await user.click(screen.getByRole('switch', { name: 'Include project name on cover' }))
  expect(preview).not.toHaveTextContent('Export test')
  expect(preview).toHaveTextContent('Client')
  await user.click(screen.getByRole('switch', { name: 'Include client name on cover' }))
  expect(preview).not.toHaveTextContent('Client')
  await user.click(screen.getByRole('button', { name: 'Continue' }))
  await user.click(screen.getByRole('button', { name: 'Continue' }))
  await user.click(screen.getByRole('button', { name: 'Download PDF' }))
  await waitFor(() => expect(mocks.download).toHaveBeenCalled())
  expect(mocks.create.mock.calls[0]?.[0]).toMatchObject({ includeProjectName: false, includeClientName: false, brief: { project: { name: 'Export test', clientName: 'Client' } } })
  expect(save).not.toHaveBeenCalled()
})
it('shows the complete saved range alongside only its matching sun periods', async () => {
  const brief = createBrief({ name: 'Range', clientName: 'Client', shoots: [{ date: '2026-09-19', time: '10:00', endTime: '12:00' }] })
  const user = userEvent.setup()
  render(<PdfExportDialog brief={brief} editable={false} captureRef={{ current: null }} onSaveNotes={vi.fn()} onClose={vi.fn()} />)
  await user.click(screen.getByRole('button', { name: 'Continue' }))
  await user.click(screen.getByRole('button', { name: 'Continue' }))
  const review = within(screen.getByLabelText('Calculated sun times'))
  expect(review.getByText('Daytime', { exact: true })).toBeVisible()
  expect(review.queryByText('Sunset', { exact: true })).not.toBeInTheDocument()
  expect(review.getByText('Planned shoot times: 10:00 - 12:00')).toBeVisible()
})
